# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

name: create-build-tag

outputs:
  build_tag:
    description: 'The generated build tag'
    value: ${{ steps.create-build-tag.outputs.build_tag }}
runs:
  using: "composite"
  steps:
    - name: Create build tag
      id: create-build-tag
      env:
        # head_ref is available when a pull request triggers workflow, ref_name contains branch name outside of pull requests
        BRANCH_NAME_RAW: ${{ github.head_ref || github.ref_name }}
        COMMIT_SHA_RAW: ${{ github.sha }}
      run: |
        DATETIME=`date -u +"%Y-%m-%dT%H-%M-%S"`
        BRANCH_NAME=`echo "${BRANCH_NAME_RAW}" | cut -c1-20 | sed 's|/|-|g'`
        COMMIT_SHA=`echo "${COMMIT_SHA_RAW}" | cut -c 1-7`
        echo "build_tag=${BRANCH_NAME}-${DATETIME}-${COMMIT_SHA}" >> "$GITHUB_OUTPUT"
      shell: bash